---
- name: In-Memory inventory playbook
  hosts: localhost
  tasks:
    - name: show user id
      command: id
      register: show_user
    
    - debug:
        var: show_user

    - name: Fetch Instance Info
      os_server_info:
        cloud: openstack
      register: result
      ignore_errors: yes

    - debug:
        var: result

    - name: Add host
      add_host:
        name: "{{ item.public_v4 }}"
        group: "{{ item.metadata.group }}"
      with_items: "{{result.openstack_servers}}"

    - name: Add host
      add_host:
        name: "{{ item.public_v4 }}"
        group: "{{ item.metadata.deployment_name }}"
      with_items: "{{result.openstack_servers}}"
